export const RESET_ACTION = 'RESET_ACTION';
export const ACTION_CONFIG_SERVICE_URL = 'ACTION_CONFIG_SERVICE_URL';

export const USER_DATA = 'USER_DATA';

export const AUTH_LINE_ERROR = 'AUTH_LINE_ERROR';
export const AUTH_LINE_SUCCESS = 'AUTH_LINE_SUCCESS';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_CLEAR_STATE = 'AUTH_CLEAR_STATE';